// @ts-check
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightGiscus from 'starlight-giscus';

// Starlight `autogenerate` does not work with this site's custom content
// loader (`base: './wiki'` in src/content.config.ts) -- it resolves `directory`
// against src/content/docs/ which does not exist here. Build the items
// programmatically from the wiki/ directory instead.
function sidebarFromWiki(dir) {
  const fullPath = path.join('./wiki', dir);
  if (!fs.existsSync(fullPath)) return [];
  return fs.readdirSync(fullPath)
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ slug: `${dir}/${f.replace(/\.md$/, '')}` }));
}

// https://astro.build/config
export default defineConfig({
  site: 'https://docs.j0kz.dev',
  base: '/',
  integrations: [
    mermaid({
      theme: 'forest',
      autoTheme: true,
    }),
    starlight({
      title: 'jkz docs',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/j0KZ/jkz-docs' },
      ],
      // Sidebar is an explicit IA (WG-50 / Phase 1, extended in Phase 2).
      // Order is deterministic: items render in the order declared below.
      // Get started + Build + Reference top groups are manual; the Agents
      // group and the API subgroup under Reference are autogenerated lists,
      // alphabetized by filename via sidebarFromWiki(). Autogeneration lets
      // the parallel Phase-2 agent-page issues (WG-59..62) drop a markdown
      // file into wiki/agents/ without touching this config.
      sidebar: [
        {
          label: 'Get started',
          items: [
            { label: 'Home', link: '/' },
            { slug: 'get-started/quickstart' },
            { slug: 'get-started/why-jkz' },
            { slug: 'get-started/how-jkz-works' },
          ],
        },
        {
          label: 'Build',
          items: [
            { slug: 'build/coming-soon' },
          ],
        },
        {
          label: 'Agents',
          items: sidebarFromWiki('agents'),
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/architecture' },
            { slug: 'reference/cli' },
            { slug: 'reference/changelog' },
            { slug: 'reference/design-decisions' },
            {
              label: 'API',
              collapsed: true,
              items: sidebarFromWiki('api-reference'),
            },
          ],
        },
      ],
      plugins: [
        starlightGiscus({
          repo: 'j0KZ/jkz-docs',
          repoId: 'R_kgDOSYL5XA',
          category: 'Wiki feedback',
          categoryId: 'DIC_kwDOSYL5XM4C9Eg2',
          mapping: 'pathname',
          reactions: true,
          inputPosition: 'bottom',
          theme: { light: 'light', dark: 'dark_dimmed' },
          lazy: true,
        }),
      ],
    }),
  ],
});
