// @ts-check
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightGiscus from 'starlight-giscus';

// Starlight `autogenerate` does not work with this site's custom content
// loader (`base: './wiki'` in src/content.config.ts) -- it resolves `directory`
// against src/content/docs/ which does not exist here. Build the items
// programmatically from the wiki/ directory instead.
function sidebarFromWiki(dir) {
  const fullPath = path.join('./wiki', dir);
  if (!fs.existsSync(fullPath)) return [];
  return fs.readdirSync(fullPath)
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ slug: `${dir}/${f.replace(/\.md$/, '')}` }));
}

// https://astro.build/config
export default defineConfig({
  site: 'https://docs.j0kz.dev',
  base: '/',
  integrations: [
    mermaid({
      theme: 'forest',
      autoTheme: true,
    }),
    starlight({
      title: 'jkz docs',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/j0KZ/jkz-docs' },
      ],
      // Sidebar is an explicit three-group IA (WG-50 / Phase 1).
      // Order is deterministic: items render in the order declared below.
      // Get started + Build + Reference top groups are manual; the API
      // subgroup under Reference is the only autogenerated list and is
      // alphabetized by filename via sidebarFromWiki().
      sidebar: [
        {
          label: 'Get started',
          items: [
            { label: 'Home', link: '/' },
            { slug: 'get-started/quickstart' },
            { slug: 'get-started/why-jkz' },
            { slug: 'get-started/how-jkz-works' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { slug: 'concepts/worktree-isolation' },
            { slug: 'concepts/merge-gate' },
            { slug: 'concepts/cross-chat' },
          ],
        },
        {
          label: 'Build',
          items: [
            { slug: 'build/lightweight-routes' },
            { slug: 'build/coming-soon' },
          ],
        },
        {
          // Agent reference pages, grouped by pipeline phase. Plan phase
          // (WG-59) ships first, then Build phase (WG-60); QA / Utility
          // pages land in later WG issues. Order within a phase follows
          // the deliberation flow, not the alphabet.
          label: 'Agents',
          items: [
            { slug: 'agents/architect' },
            { slug: 'agents/auditor' },
            { slug: 'agents/curator' },
            { slug: 'agents/builder' },
            { slug: 'agents/judge' },
            { slug: 'agents/inspector' },
            { slug: 'agents/doctor' },
            { slug: 'agents/lens' },
            { slug: 'agents/sentinel' },
          ],
        },
        {
          // Command reference pages. Unlike Agents, the order here is not
          // semantic, so the list is autogenerated (alphabetized by filename)
          // via sidebarFromWiki(). New command pages (WG-63 / WG-64) only need
          // to add a file under wiki/commands/ — no edit to this config.
          label: 'Commands',
          items: sidebarFromWiki('commands'),
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/architecture' },
            { slug: 'reference/cli' },
            { slug: 'reference/changelog' },
            { slug: 'reference/design-decisions' },
            {
              label: 'API',
              collapsed: true,
              items: sidebarFromWiki('api-reference'),
            },
          ],
        },
      ],
      plugins: [
        starlightGiscus({
          repo: 'j0KZ/jkz-docs',
          repoId: 'R_kgDOSYL5XA',
          category: 'Wiki feedback',
          categoryId: 'DIC_kwDOSYL5XM4C9Eg2',
          mapping: 'pathname',
          reactions: true,
          inputPosition: 'bottom',
          theme: { light: 'light', dark: 'dark_dimmed' },
          lazy: true,
        }),
      ],
    }),
  ],
});
