// @ts-check
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightGiscus from 'starlight-giscus';

// Starlight `autogenerate` does not work with this site's custom content
// loader (`base: './wiki'` in src/content.config.ts) -- it resolves `directory`
// against src/content/docs/ which does not exist here. Build the items
// programmatically from the wiki/ directory instead.
function sidebarFromWiki(dir) {
  const fullPath = path.join('./wiki', dir);
  if (!fs.existsSync(fullPath)) return [];
  return fs.readdirSync(fullPath)
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ slug: `${dir}/${f.replace(/\.md$/, '')}` }));
}

// https://astro.build/config
export default defineConfig({
  site: 'https://docs.j0kz.dev',
  base: '/',
  integrations: [
    mermaid({
      theme: 'forest',
      autoTheme: true,
    }),
    starlight({
      title: 'jkz docs',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/j0KZ/jkz-docs' },
      ],
      // Sidebar is an explicit three-group IA (WG-50 / Phase 1).
      // Order is deterministic: items render in the order declared below.
      // Get started + Build + Reference top groups are manual; the API
      // subgroup under Reference is the only autogenerated list and is
      // alphabetized by filename via sidebarFromWiki().
      sidebar: [
        {
          label: 'Get started',
          items: [
            { label: 'Home', link: '/' },
            { slug: 'get-started/install' },
            { slug: 'get-started/quickstart' },
            { slug: 'get-started/why-jkz' },
            { slug: 'get-started/how-jkz-works' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { slug: 'concepts/pipeline' },
            { slug: 'concepts/issue-types' },
            { slug: 'concepts/evidence-hierarchy' },
            { slug: 'concepts/ambiguity-gate' },
            { slug: 'concepts/merge-gate' },
            { slug: 'concepts/worktree-isolation' },
            { slug: 'concepts/cross-chat' },
            { slug: 'concepts/signal-format' },
            { slug: 'concepts/context-management' },
            { slug: 'concepts/fallback' },
            { slug: 'concepts/plugin-mode' },
          ],
        },
        {
          label: 'Build',
          items: [
            { slug: 'build/run-a-pipeline' },
            { slug: 'build/lightweight-routes' },
          ],
        },
        {
          // Command reference pages, consolidated into a single group after
          // WG-63/64/65 each shipped its own slice (the concurrent merges left
          // three separate Commands groups). Order is by category, not the
          // alphabet (consistent with the Agents group): core pipeline first,
          // then lightweight/lifecycle, then ancillary. New command pages
          // insert their slug into the matching category below.
          label: 'Commands',
          items: [
            // core pipeline
            { slug: 'commands/plan' },
            { slug: 'commands/build' },
            { slug: 'commands/review' },
            { slug: 'commands/qa' },
            { slug: 'commands/pipeline' },
            // lightweight & lifecycle
            { slug: 'commands/quick' },
            { slug: 'commands/fix' },
            { slug: 'commands/resume' },
            { slug: 'commands/start' },
            { slug: 'commands/status' },
            { slug: 'commands/issue' },
            { slug: 'commands/refine' },
            { slug: 'commands/save' },
            { slug: 'commands/load' },
            { slug: 'commands/quit' },
            { slug: 'commands/new-chat' },
            // ancillary
            { slug: 'commands/debate' },
            { slug: 'commands/ask' },
            { slug: 'commands/research' },
            { slug: 'commands/vault' },
            { slug: 'commands/health' },
            // quality & audit
            { slug: 'commands/bugs' },
            { slug: 'commands/quality' },
            { slug: 'commands/deps' },
            { slug: 'commands/perf-audit' },
            { slug: 'commands/e2e' },
            { slug: 'commands/skill-audit' },
            { slug: 'commands/simplify' },
            { slug: 'commands/deslop' },
            // dev & review workflow
            { slug: 'commands/commit' },
            { slug: 'commands/cr-fix' },
            { slug: 'commands/ship' },
            { slug: 'commands/dev-self-review' },
            { slug: 'commands/doc-sync' },
            // consultation, analytics & memory (WG-71)
            { slug: 'commands/cost' },
            { slug: 'commands/insights' },
            { slug: 'commands/calibrate' },
            { slug: 'commands/memory-status' },
            { slug: 'commands/memory-review' },
            { slug: 'commands/memory-promote' },
          ],
        },
        {
          // Agent reference pages, grouped by pipeline phase. Plan phase
          // (WG-59) ships first, then Build phase (WG-60); QA / Utility
          // pages land in later WG issues. Order within a phase follows
          // the deliberation flow, not the alphabet.
          label: 'Agents',
          items: [
            { slug: 'agents/architect' },
            { slug: 'agents/auditor' },
            { slug: 'agents/curator' },
            { slug: 'agents/builder' },
            { slug: 'agents/judge' },
            { slug: 'agents/inspector' },
            { slug: 'agents/doctor' },
            { slug: 'agents/lens' },
            { slug: 'agents/sentinel' },
            { slug: 'agents/librarian' },
            { slug: 'agents/classifier' },
            { slug: 'agents/orchestrator' },
          ],
        },
        {
          // Subsystem deep-dives (Layer B). Pages here document a single
          // long-lived subsystem end to end; they cross-link Concepts.
          // New subsystem pages insert their slug below.
          label: 'Subsystems',
          items: [
            { slug: 'subsystems/classifier-and-alignment' },
            { slug: 'subsystems/hermes' },
            { slug: 'subsystems/coderabbit' },
            { slug: 'subsystems/hooks' },
            { slug: 'subsystems/mcp-servers' },
            { slug: 'subsystems/telegram-bot' },
            { slug: 'subsystems/wiki-generator' },
          ],
        },
        {
          // Operations deep-dives (Layer C). Pages here document how the
          // running system is operated, observed, and kept healthy end to end.
          // New operations pages insert their slug below rather than creating
          // a second Operations group.
          label: 'Operations',
          items: [
            { slug: 'operations/memory' },
            { slug: 'operations/slos-and-monitoring' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/architecture' },
            { slug: 'reference/cli' },
            { slug: 'reference/skills' },
            { slug: 'reference/changelog' },
            { slug: 'reference/design-decisions' },
            {
              label: 'API',
              collapsed: true,
              items: sidebarFromWiki('api-reference'),
            },
          ],
        },
      ],
      plugins: [
        starlightGiscus({
          repo: 'j0KZ/jkz-docs',
          repoId: 'R_kgDOSYL5XA',
          category: 'Wiki feedback',
          categoryId: 'DIC_kwDOSYL5XM4C9Eg2',
          mapping: 'pathname',
          reactions: true,
          inputPosition: 'bottom',
          theme: { light: 'light', dark: 'dark_dimmed' },
          lazy: true,
        }),
      ],
    }),
  ],
});
